pipeline:
  run-tests:
    image: python:3.12-slim
    commands:
      - pip install uv 
      - uv pip install --python /usr/local/bin/python3 --no-cache -r requirements.txt
      - uv pip install --python /usr/local/bin/python3 -e .
      - uv pip install --python /usr/local/bin/python3 pytest
      - pytest ./test/test_user.py
      - pytest ./test/test_data.py
